const FLAGS: Record<string, string> = {
  Alemania: '🇩🇪',
  'Arabia Saudita': '🇸🇦',
  Argelia: '🇩🇿',
  Argentina: '🇦🇷',
  Australia: '🇦🇺',
  Austria: '🇦🇹',
  Bélgica: '🇧🇪',
  'Bosnia y Herzegovina': '🇧🇦',
  Brasil: '🇧🇷',
  'Cabo Verde': '🇨🇻',
  Camerún: '🇨🇲',
  Canadá: '🇨🇦',
  Chequia: '🇨🇿',
  Colombia: '🇨🇴',
  'Corea del Sur': '🇰🇷',
  'Costa de Marfil': '🇨🇮',
  Croacia: '🇭🇷',
  Curazao: '🇨🇼',
  Ecuador: '🇪🇨',
  Egipto: '🇪🇬',
  'Emiratos Árabes Unidos': '🇦🇪',
  Escocia: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  España: '🇪🇸',
  'Estados Unidos': '🇺🇸',
  Francia: '🇫🇷',
  Ghana: '🇬🇭',
  Haití: '🇭🇹',
  Inglaterra: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  Irak: '🇮🇶',
  Irán: '🇮🇷',
  Japón: '🇯🇵',
  Jordania: '🇯🇴',
  Marruecos: '🇲🇦',
  México: '🇲🇽',
  Noruega: '🇳🇴',
  'Nueva Zelanda': '🇳🇿',
  'Países Bajos': '🇳🇱',
  Panamá: '🇵🇦',
  Paraguay: '🇵🇾',
  Portugal: '🇵🇹',
  Qatar: '🇶🇦',
  Senegal: '🇸🇳',
  Sudáfrica: '🇿🇦',
  Suecia: '🇸🇪',
  Suiza: '🇨🇭',
  Túnez: '🇹🇳',
  Turquía: '🇹🇷',
  Uruguay: '🇺🇾',
}

export function flag(team: string): string {
  return FLAGS[team] ?? ''
}
